local plugins = {
	require("plugins.telescope"),
	require("plugins.harpoon"),
	require("plugins.autopairs"),
	require("plugins.lush"),
	require("plugins.mason"),
	require("plugins.conform"),
	require("plugins.lint"),
	require("plugins.treesitter"),
	require("plugins.cmp"),
	require("plugins.theme"),
	require("plugins.vtsls"),
	require("plugins.colortils"),
	require("plugins.hexokinase"),
	require("plugins.gv"),
	require("plugins.gitgutter"),
	require("plugins.lualine"),
	require("plugins.commentary"),
	require("plugins.rainbow"),
	require("plugins.octo"),
	require("plugins.todo"),
	require("plugins.leap"),
	require("plugins.undotree"),
}

return plugins
